blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.all_blogs, name="all_blogs"),
    path("<int:blog_id>", views.detail, name="detail")
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("portfolio.urls")),
    path('blog/', include("blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

portfolio/urls.py
from . import views
from django.urls import path

app_name = "portfolio"
urlpatterns = [
    path("", views.home, name="home"),
    path("resume", views.resume, name="resume")
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model) :
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model) :
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self) :
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def all_blogs(request) :
    blog_count = Blog.objects.count
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {
        "blogs": blogs,
        "count": blog_count
    })

def detail(request, blog_id) :
    blog = get_object_or_404(Blog, pk=blog_id )
    return render(request, "blog/detail.html", {
        "blog": blog
    })

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

# Create your views here.
def home(request) :
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {
        'projects': projects        
    })

def resume(request) :
    return HttpResponse("<h1 style='text-align:center;'>Coming soon :)</h1>")


def icons(request) :
    return render(request, 'portfolio/Untitled.html')

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="font-weight-bold text-center" id="blogtitle">Blog</h1>

<h3 class="text-center mb-5">Deva has written {{ count }} blog{{ count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
    <div class="col-md-10">
        <a href="{% url 'blog:detail' blog.id %}">
            <h2>{{ blog.title }}</h2>
        </a>
        <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
        <h4>{{ blog.description|striptags|truncatechars:50 }}</h4>
    </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'portfolio/memoji.png' %}">

    <title>DevaSenan</title>
    <style>
        .navbar-nav .nav-link {
            color: rgba(0,0,0,1) !important;
        }

        .navbar-nav .nav-link:hover {
            color: rgb(51, 255, 153) !important;
        }

        body {
            font-family: 'Lato', sans-serif;
        }
    </style>

</head>

<body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'portfolio:home' %}">
                <img src="{% static 'portfolio/memoji.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span>DevaSenan</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse text-center" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'portfolio:resume' %}" target="_blank">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="{% url 'blog:all_blogs' %}">Blog</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container" style="margin-bottom: 100px; padding: 30px;">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="page-footer font-small fixed-bottom">
        
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3" style="background-color: black; color: white; opacity: 75%;">
            <a href="https://www.instagram.com/devasenan134/" target="_blank">Instagram</a> | <a
                href="https://www.linkedin.com/in/deva-senan-4b9a67161/" target="_blank">LinkedIn</a> | <a
                href="https://twitter.com/devasenan134" target="_blank">Twitter</a>
        </div>
        <!-- Copyright -->
    
    </footer>
    <!-- Footer -->


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/airport_tower.jpg' %}" class="img-fluid">
    </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
        <h1 id="hometext" class="font-weight-bold">DevaSenan</h1>
    </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

        {% if project.url %}
        <a href="{{ project.url }}">
            <img src="{{ project.image.url }}" class="img-fluid mb-2">
        </a>
        {% else %}

        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>

    </div>
    {% endfor %}
</div>

{% endblock %}

portfolio/templates/portfolio/icons.html
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
        <head>
            
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
                integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
            <!--Bootstrap for media icons-->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="{% static 'portfolio/style_icon.css' %}">
            
        </head>
        <body>
            <div class="d-flex justify-content-center">
                <div class="row">
                    <div>
                        <ul class="social-network social-circle">
                            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="icoInstagram" title="Instagram"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </body>
    </html>